# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 01:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_auto_20170925_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualification',
            name='subject',
        ),
        migrations.AddField(
            model_name='qualification',
            name='teacher_subject',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Api.Teacher_Subject'),
            preserve_default=False,
        ),
    ]
