# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 03:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_qualification_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualification',
            name='detail',
        ),
    ]
