# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0007_auto_20170925_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attorney',
            name='birthdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='birthdate',
            field=models.DateField(),
        ),
    ]
