# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0008_auto_20170926_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
    ]
