# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0010_enrollment_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='teacher',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Api.Teacher'),
            preserve_default=False,
        ),
    ]
